language: go

install:
  - go get -d -v ./...
  - go get -u github.com/stretchr/testify/require
  - go get -u github.com/google/gofuzz
  - go get -u github.com/codahale/chacha20poly1305
  - go get -u github.com/codahale/etm

script: make clean && make test && make test

go:
  - 1.3
  - 1.4
  - tip
